name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}-${plugin.platform}
api-version: '${minecraft.api.version}'
author: pupskuchen
website: ${project.url}
load: STARTUP
description: TimeControl built explicitly for ${plugin.platform}
